---
# - name: Display all open ports
#   hosts: all
#   tasks:
#     - name: Gather facts on listening ports
#       community.general.listen_ports_facts:
#       register: result

#     - debug:
#         var: result.ansible_facts.tcp_listen
        
- hosts: all
  become: true
  tasks:
    - block:
        - import_role:
            name: container-engine

- hosts: exporters
  become: true
  tasks:
    - block:
        - import_role:
            name: node-exporter
        - import_role:
            name: znapzend-exporter

- hosts: metrics
  become: true
  tasks:
    - block:
        - import_role:
            name: prometheus
        - import_role:
            name: grafana

- name: Display all open ports
  hosts: all
  tasks:
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
      register: result

    - debug:
        var: result.ansible_facts.tcp_listen
        